In [ ]:
# https://simdkalman.readthedocs.io/en/latest/

In [1]:
import simdkalman

In [2]:
import numpy as np

In [3]:
kf = simdkalman.KalmanFilter(
    state_transition = [[1, 1], [0, 1]],
    process_noise = np.diag([0.1, 0.01]),
    observation_model = np.array([[1, 0]]),
    observation_noise = 1.0)

In [4]:
kf

In [5]:
import numpy.random as random

In [6]:
data = random.normal(size = (100, 200))

In [7]:
data[random.uniform(size = data.shape) < 0.1] = np.nan

In [8]:
data

array([[ 2.37920007, -1.13287279,         nan, ...,         nan,
                nan,         nan],
       [ 0.66598332,  1.62562881, -0.80119324, ..., -1.0215095 ,
         0.80346308,  0.1669901 ],
       [        nan,  0.69438923, -0.63443874, ..., -1.63140693,
         0.44706784, -0.43786343],
       ...,
       [ 1.05763998,  0.4375143 , -0.51810554, ..., -0.58233269,
        -1.23751215, -0.27953639],
       [ 0.4385245 ,  2.59502333, -0.51447132, ..., -2.03160024,
         0.16200312,  0.19887844],
       [-0.1966889 , -2.6401791 , -1.96880625, ..., -0.42949483,
        -0.24846797, -0.12241985]])

In [9]:
smoothed = kf.smooth(data,
                    initial_value = [1, 0], 
                    initial_covariance = np.eye(2) * 0.5)

In [11]:
print('mean')
print(smoothed.states.mean[1, 2, :])

mean
[ 0.34998615 -0.09485397]


In [12]:
print('covariance')
print(smoothed.states.cov[1, 2, :, :])

covariance
[[ 0.18381972 -0.00725583]
 [-0.00725583  0.02561241]]


In [13]:
smoothed

In [14]:
print(smoothed)

states:
  mean:
    [[[ 1.00332381 -0.09040144]
      [ 0.77599951 -0.07851718]
      [ 0.7514467  -0.07202936]
      ...
      [ 0.55484535  0.12258403]
      [ 0.67742938  0.12258403]
      [ 0.80001341  0.12258403]]
    
     [[ 0.7555146  -0.11256091]
      [ 0.60300974 -0.11081773]
      [ 0.34998615 -0.09485397]
      ...
      [ 0.14651146 -0.0036595 ]
      [ 0.20046559 -0.00392811]
      [ 0.19385135 -0.00392811]]
    
     [[ 0.7321282  -0.08169576]
      [ 0.59685808 -0.07797224]
      [ 0.45555836 -0.06791597]
      ...
      [-0.65583863 -0.0479502 ]
      [-0.58332505 -0.04620775]
      [-0.61210831 -0.04620775]]
    
     ...
    
     [[ 0.62659574 -0.13757782]
      [ 0.37123264 -0.12855084]
      [ 0.11826836 -0.10708253]
      ...
      [-0.65686139 -0.04583611]
      [-0.71213331 -0.0415259 ]
      [-0.71055714 -0.0415259 ]]
    
     [[ 0.82738547 -0.12316719]
      [ 0.70858147 -0.12606685]
      [ 0.39823362 -0.11053842]
      ...
      [-0.64717511  0.05783418]


In [15]:
print(kf)

In [16]:
predicted = kf.predict(data[1, :], 123)

In [17]:
pred_mean = predicted.observations.mean[2]

In [18]:
pred_stdev = np.sqrt(predicted.observations.cov[2])

In [19]:
print('%g +- %g' % (pred_mean, pred_stdev))

0.182067 +- 1.6535
